object Libs {
    const val KTX = "androidx.core:core-ktx:1.9.0"
    const val LIFECYCLE = "androidx.lifecycle:lifecycle-runtime-ktx:2.6.2"
    const val COMPOSE = "androidx.activity:activity-compose:1.7.2"
    const val COMPOSE_PLATFORM = "androidx.compose:compose-bom:2023.03.00"
    const val COMPOSE_UI = "androidx.compose.ui:ui"
    const val COMPOSE_UI_GRAPHICS = "androidx.compose.ui:ui-graphics"
    const val COMPOSE_PREVIEW = "androidx.compose.ui:ui-tooling-preview"
    const val MATERIAL = "androidx.compose.material3:material3"
    const val JUNIT = "junit:junit:4.13.2"
    const val TEST_JUNIT = "androidx.test.ext:junit:1.1.5"
    const val TEST_ESPRESSO = "androidx.test.espresso:espresso-core:3.5.1"
    const val COMPOSE_TEST_UI = "androidx.compose.ui:ui-test-junit4"
    const val COMPOSE_UI_TOOLING = "androidx.compose.ui:ui-tooling"
    const val COMPOSE_TEST_MANIFEST = "androidx.compose.ui:ui-test-manifest"
    const val HILT = "com.google.dagger:hilt-android:2.44"
    const val HILT_COMPILER = "com.google.dagger:hilt-compiler:2.44"
    const val ROOM = "androidx.room:room-runtime:2.5.2"
    const val ROOM_KTX = "androidx.room:room-ktx:2.5.2"
    const val ROOM_COMPILER = "androidx.room:room-compiler:2.5.2"
    const val RETROFIT = "com.squareup.retrofit2:retrofit:2.9.0"
    const val RETROFIT_GSON = "com.squareup.retrofit2:converter-gson:2.9.0"
}